name: Deploy

on:
  push:
    branches: [master, main]
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Generate documentation
        run: |
          if [ -f "docs/build.js" ]; then
            node docs/build.js
          fi
          echo "Documentation generation completed"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs

  update-release-assets:
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Update release descriptions
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const path = require('path');

            // Read package.json for app information
            const pkg = JSON.parse(fs.readFileSync('package.json', 'utf8'));

            const releaseBody = `
            ## ${pkg.description || 'DAO Copilot Release'}

            Version: **${pkg.version}**

            ### What's New
            - Cross-platform Electron application
            - Audio capture and transcription capabilities
            - Real-time speech-to-text processing
            - Google Cloud Speech integration

            ### Downloads
            Choose the installer for your operating system:

            | Platform | File Type | Description |
            |----------|-----------|-------------|
            | Windows | .exe | Windows Installer |
            | macOS | .dmg | macOS Disk Image |
            | Linux | .AppImage | Portable Linux Application |
            | Linux | .deb | Debian Package |
            | Linux | .snap | Snap Package |

            ### Installation
            1. Download the appropriate installer for your platform
            2. Run the installer and follow the setup instructions
            3. Launch the application from your applications menu

            ### System Requirements
            - **Windows**: Windows 10 or later
            - **macOS**: macOS 10.14 or later
            - **Linux**: Ubuntu 18.04 or equivalent

            ### Support
            If you encounter any issues, please check our [documentation](https://github.com/${context.repo.owner}/${context.repo.repo}/blob/master/README.md) or [open an issue](https://github.com/${context.repo.owner}/${context.repo.repo}/issues).
            `;

            // Update the release
            await github.rest.repos.updateRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: context.payload.release.id,
              body: releaseBody
            });
