name: Sync Taskmaster to GitHub Projects

on:
  # Run on manual trigger
  workflow_dispatch:
    inputs:
      dry_run:
        description: 'Dry run (no changes made)'
        required: false
        type: boolean
        default: true
      command:
        description: 'Command to run'
        required: true
        type: choice
        options:
          - sync
          - fetch
          - list
        default: sync
  
  # Run on push to master when tasks.json changes
  push:
    branches:
      - master
      - main
    paths:
      - '.taskmaster/tasks/tasks.json'

jobs:
  sync-to-project:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      # Required for GitHub Projects
      # Note: This requires a PAT with project scope in secrets
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Determine command
        id: command
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "command=${{ github.event.inputs.command }}" >> $GITHUB_OUTPUT
            if [ "${{ github.event.inputs.dry_run }}" == "true" ]; then
              echo "flags=" >> $GITHUB_OUTPUT
            else
              echo "flags=--live" >> $GITHUB_OUTPUT
            fi
          else
            # Auto-sync on push (dry run by default for safety)
            echo "command=sync" >> $GITHUB_OUTPUT
            echo "flags=" >> $GITHUB_OUTPUT
          fi
      
      - name: Run GitHub Projects Sync
        env:
          GITHUB_TOKEN: ${{ secrets.PROJECTS_SYNC_TOKEN }}
        run: |
          if [ -z "$GITHUB_TOKEN" ]; then
            echo "⚠️  Warning: PROJECTS_SYNC_TOKEN secret is not set"
            echo "   The sync will not run. Please add a GitHub PAT with project scope to secrets."
            exit 1
          fi
          
          npx tsx scripts/github-projects-sync.ts ${{ steps.command.outputs.command }} ${{ steps.command.outputs.flags }}
      
      - name: Create summary
        if: always()
        run: |
          echo "## GitHub Projects Sync Result" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- **Command**: ${{ steps.command.outputs.command }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Mode**: ${{ steps.command.outputs.flags == '--live' && 'Live' || 'Dry Run' }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Triggered by**: ${{ github.event_name }}" >> $GITHUB_STEP_SUMMARY
          if [ "${{ github.event_name }}" == "push" ]; then
            echo "- **Commit**: ${{ github.sha }}" >> $GITHUB_STEP_SUMMARY
          fi
