name: Taskmaster Issue Sync

on:
  issues:
    types: [closed, reopened]
  workflow_dispatch:
    inputs:
      sync_direction:
        description: "Sync direction"
        required: true
        default: "issue-to-task"
        type: choice
        options:
          - issue-to-task
          - task-to-issue

jobs:
  sync-issue-to-task:
    if: github.event_name == 'issues' || github.event.inputs.sync_direction == 'issue-to-task'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install task-master
        run: npm install -g task-master-ai

      - name: Extract Task ID from Issue
        id: extract_task
        run: |
          TITLE="${{ github.event.issue.title }}"
          TASK_ID=$(echo "$TITLE" | grep -oE '\[Task [0-9.]+\]' | grep -oE '[0-9.]+' || echo "")
          echo "task_id=$TASK_ID" >> $GITHUB_OUTPUT

      - name: Update Task Status
        if: steps.extract_task.outputs.task_id != ''
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          PERPLEXITY_API_KEY: ${{ secrets.PERPLEXITY_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          TASK_ID="${{ steps.extract_task.outputs.task_id }}"

          if [ "${{ github.event.action }}" = "closed" ]; then
            task-master set-status --id="$TASK_ID" --status=done
            echo "✅ Marked Task $TASK_ID as done"
          elif [ "${{ github.event.action }}" = "reopened" ]; then
            task-master set-status --id="$TASK_ID" --status=in-progress
            echo "🔄 Marked Task $TASK_ID as in-progress"
          fi

      - name: Commit updated tasks
        if: steps.extract_task.outputs.task_id != ''
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .taskmaster/tasks/
          git diff --staged --quiet || git commit -m "chore: sync task ${{ steps.extract_task.outputs.task_id }} from issue #${{ github.event.issue.number }}"
          git push

      - name: Comment on Issue
        if: steps.extract_task.outputs.task_id != ''
        uses: actions/github-script@v7
        with:
          script: |
            const taskId = '${{ steps.extract_task.outputs.task_id }}';
            const action = '${{ github.event.action }}';
            const emoji = action === 'closed' ? '✅' : '🔄';
            const status = action === 'closed' ? 'done' : 'in-progress';

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `${emoji} Taskmaster Task ${taskId} has been automatically marked as **${status}**.`
            });

  sync-tasks-to-issues:
    if: github.event.inputs.sync_direction == 'task-to-issue'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: |
          npm install -g task-master-ai
          sudo apt-get install -y jq

      - name: Create Issues from Tasks
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          PERPLEXITY_API_KEY: ${{ secrets.PERPLEXITY_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          chmod +x .github/scripts/sync-taskmaster-github.sh
          .github/scripts/sync-taskmaster-github.sh master pending
